# Generated by Django 2.0.5 on 2018-05-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
